/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class loanApp2 extends javax.swing.JFrame {

    /**
     * Creates new form loanApp2
     */
    public loanApp2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loanAmount = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        loanRepayment = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalInterest = new javax.swing.JTextField();
        loanDuration = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (33).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(904, 655));
        setPreferredSize(new java.awt.Dimension(904, 655));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LOAN APPLICATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 30, 490, 64);

        loanAmount.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(loanAmount);
        loanAmount.setBounds(20, 180, 200, 40);

        calculate.setBackground(new java.awt.Color(255, 255, 255));
        calculate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        calculate.setForeground(new java.awt.Color(0, 0, 0));
        calculate.setText("CALCULATE");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate);
        calculate.setBounds(320, 300, 270, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TOTAL REPAYMENT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(11, 577, 180, 25);

        loanRepayment.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(loanRepayment);
        loanRepayment.setBounds(192, 571, 197, 38);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(791, 571, 90, 38);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ENTER LOAN AMOUNT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 210, 25);

        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 180, 64, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TOTAL INTEREST");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(428, 577, 146, 25);

        totalInterest.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totalInterest);
        totalInterest.setBounds(582, 571, 197, 38);

        loanDuration.setBackground(new java.awt.Color(255, 255, 255));
        loanDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanDurationActionPerformed(evt);
            }
        });
        getContentPane().add(loanDuration);
        loanDuration.setBounds(680, 180, 200, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ENTER  DURATION");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 150, 180, 25);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        output.setBackground(new java.awt.Color(255, 255, 255));
        output.setColumns(20);
        output.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        output.setForeground(new java.awt.Color(0, 0, 0));
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(24, 350, 860, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (33).jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 904, 660);

        setBounds(0, 0, 918, 662);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
loanAmount.setText("");
    loanDuration.setText("");
    
    // Clear out the large center breakdown box
    output.setText("");
    
    // Clear out the final summary text fields
    loanRepayment.setText("");
    totalInterest.setText("");  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
    try {
        // 1. Clear previous text from the large breakdown output area
        output.setText(""); 
        
        // 2. Read values from your text fields using your variable names
        double loanAmt = Double.parseDouble(loanAmount.getText());
        int totalMonths = Integer.parseInt(loanDuration.getText());

        // 3. Run validation checks using pop-up dialog boxes
        if (loanAmt <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR: Loan Amount must be greater than zero.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }
        
        if (totalMonths <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "ERROR: Loan Duration must be greater than zero.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Run your exact math calculations
        double monthlyRate = 1.5;
        double currentBalance = loanAmt;
        double MonthlyRepayment = loanAmt / totalMonths;
        double rateFraction = monthlyRate / 100.0;

        double totalMonthlyRepayment = 0;
        double totalInterestPaid = 0;
        double totalOverallPaid = 0;

        // Construct the tabular header for your 'output' box
        StringBuilder breakdown = new StringBuilder();
        breakdown.append("LOAN BREAKDOWN\n");
        breakdown.append("------------------------------------------------------------------------------------------------------\n");
        breakdown.append(String.format("%-10s | %-20s | %-20s | %-20s\n", "Month", "Monthly Payment", "Monthly Interest", "Monthly Repayment"));
        breakdown.append("------------------------------------------------------------------------------------------------------\n");

        for (int month = 1; month <= totalMonths; month++) {
            double interestAmount = currentBalance * rateFraction;
            double totalMonthlyPayment = MonthlyRepayment + interestAmount;

            totalMonthlyRepayment += MonthlyRepayment;
            totalInterestPaid += interestAmount;
            totalOverallPaid += totalMonthlyPayment;

            breakdown.append(String.format("%-10d | NGN%-18.2f | NGN%-18.2f | NGN%-18.2f\n",
                    month, MonthlyRepayment, interestAmount, totalMonthlyPayment));

            currentBalance -= MonthlyRepayment;
        }

        // 5. Send results to your respective output components
        output.setText(breakdown.toString());
        totalInterest.setText(String.format("NGN%,.2f", totalInterestPaid));
        loanRepayment.setText(String.format("NGN%,.2f", totalOverallPaid));

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "ERROR! ENTER THE APPROPRIATE VALUE", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_calculateActionPerformed

    private void loanDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanDurationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanApp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanApp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField loanAmount;
    private javax.swing.JTextField loanDuration;
    private javax.swing.JTextField loanRepayment;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField totalInterest;
    // End of variables declaration//GEN-END:variables
}
