/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class boylesCalc extends javax.swing.JFrame {

    /**
     * Creates new form boylesCalc
     */
    public boylesCalc() {
        initComponents();
         getContentPane().setBackground(new java.awt.Color(132,156,195));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        calculate = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        result = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        choice = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inip1 = new javax.swing.JTextField();
        inip2 = new javax.swing.JTextField();
        iniv1 = new javax.swing.JTextField();
        iniv2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(132, 156, 195));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calculate.setBackground(new java.awt.Color(235, 232, 232));
        calculate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculate.setForeground(new java.awt.Color(0, 0, 0));
        calculate.setText("CALCULATE");
        calculate.setBorder(null);
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        jPanel2.add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 241, 76));

        clear.setBackground(new java.awt.Color(204, 0, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 241, 92));

        result.setBackground(new java.awt.Color(226, 219, 219));
        result.setBorder(null);
        jPanel2.add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 420, 46));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("THE RESULT =");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 119, 26));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 790, 240));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FIND ........................");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 46, -1, -1));

        choice.setBackground(new java.awt.Color(255, 255, 255));
        choice.setForeground(new java.awt.Color(0, 0, 0));
        choice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Initial Pressure (P1)", "Initial Volume (V1)", "Final Pressure (P2)", "Final Volume (V2)" }));
        choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceActionPerformed(evt);
            }
        });
        jPanel1.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 74, 720, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INITIAL PRESSURE 1 (P1)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 128, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("INITIAL PRESSURE 2 (P2)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("INITIAL VOLUME 2 (P2)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("INITIAL VOLUME 1 (V1)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        inip1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(inip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 250, 34));

        inip2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(inip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 150, 240, 31));

        iniv1.setBackground(new java.awt.Color(255, 255, 255));
        iniv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniv1ActionPerformed(evt);
            }
        });
        jPanel1.add(iniv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 250, 37));

        iniv2.setBackground(new java.awt.Color(255, 255, 255));
        iniv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniv2ActionPerformed(evt);
            }
        });
        jPanel1.add(iniv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 210, 240, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BOYLE'S LAW CALCULATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
inip1.setText("");
    inip2.setText("");
    iniv1.setText("");
    iniv2.setText("");
    result.setText("");
    
    // Reset the dropdown menu back to the first selection item
    choice.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void iniv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniv2ActionPerformed

    private void iniv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniv1ActionPerformed

    private void choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceActionPerformed
int selection = choice.getSelectedIndex();
    
    // 1. Reset all fields to editable and white background
    inip1.setEditable(true);
    inip1.setBackground(java.awt.Color.WHITE);
    
    iniv1.setEditable(true);
    iniv1.setBackground(java.awt.Color.WHITE);
    
    inip2.setEditable(true);
    inip2.setBackground(java.awt.Color.WHITE);
    
    iniv2.setEditable(true);
    iniv2.setBackground(java.awt.Color.WHITE);
    
    // Define your bluish-purple color (RGB)
    java.awt.Color lockColor = new java.awt.Color(132,156,195);
    
    // 2. Lock the target field and change its color
    if (selection == 0) {       // Finding P1
        inip1.setText("");
        inip1.setEditable(false);
        inip1.setBackground(lockColor);
    } else if (selection == 1) { // Finding V1
        iniv1.setText("");
        iniv1.setEditable(false);
        iniv1.setBackground(lockColor);
    } else if (selection == 2) { // Finding P2
        inip2.setText("");
        inip2.setEditable(false);
        inip2.setBackground(lockColor);
    } else if (selection == 3) { // Finding V2
        iniv2.setText("");
        iniv2.setEditable(false);
        iniv2.setBackground(lockColor);
    }

    }//GEN-LAST:event_choiceActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
try {
        // Get the selected position from the dropdown menu (0-indexed)
        // 0 = P1, 1 = V1, 2 = P2, 3 = V2
        int selection = choice.getSelectedIndex(); 
        
        double ans = 0;

        if (selection == 0) { // Finding Initial Pressure (inip1)
            double p2 = Double.parseDouble(inip2.getText());
            double v2 = Double.parseDouble(iniv2.getText());
            double v1 = Double.parseDouble(iniv1.getText());
            
            ans = (p2 * v2) / v1;
            result.setText(String.format("P1 = %.2f", ans));
            
        } else if (selection == 1) { // Finding Initial Volume (iniv1)
            double v2 = Double.parseDouble(iniv2.getText());
            double p2 = Double.parseDouble(inip2.getText());
            double p1 = Double.parseDouble(inip1.getText());
            
            ans = (p2 * v2) / p1;
            result.setText(String.format("V1 = %.2f", ans));
            
        } else if (selection == 2) { // Finding Final Pressure (inip2)
            double p1 = Double.parseDouble(inip1.getText());
            double v1 = Double.parseDouble(iniv1.getText());
            double v2 = Double.parseDouble(iniv2.getText());
            
            ans = (p1 * v1) / v2;
            result.setText(String.format("P2 = %.2f", ans));
            
        } else if (selection == 3) { // Finding Final Volume (iniv2)
            double p1 = Double.parseDouble(inip1.getText());
            double v1 = Double.parseDouble(iniv1.getText());
            double p2 = Double.parseDouble(inip2.getText());
            
            ans = (p1 * v1) / p2;
            result.setText(String.format("V2 = %.2f", ans));
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill the required fields with numbers.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boylesCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boylesCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boylesCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boylesCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new boylesCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JComboBox<String> choice;
    private javax.swing.JButton clear;
    private javax.swing.JTextField inip1;
    private javax.swing.JTextField inip2;
    private javax.swing.JTextField iniv1;
    private javax.swing.JTextField iniv2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField result;
    // End of variables declaration//GEN-END:variables
}
